[pytest]
testpaths = tests
filterwarnings =
    ignore::DeprecationWarning:starlette.*
    ignore::starlette.exceptions.StarletteDeprecationWarning
    ignore:The 'generic' unit for NumPy timedelta:DeprecationWarning
